PUREWEBHOME = ENV["PUREWEB_HOME"]
PUREWEBLIBS = ENV["PUREWEB_LIBS"]

PROJECT="Asteroids"

desc "Setup #{PROJECT}"
task :setup do
end

desc "Clean #{PROJECT}"
task :clean do	
end

desc "Deploy #{PROJECT}"
task :deploy do
	Rake::Task[:stage].invoke
end

desc "Package #{PROJECT}"
task :package do
	puts "Need to implement PACKAGE for #{PROJECT}"
end

desc "Package clean #{PROJECT}"
task :packageclean do
	puts "Need to implement PACKAGECLEAN for #{PROJECT}"
end 

desc "Stage #{PROJECT}"
task :stage do	
	FileUtils.mkdir_p("#{PUREWEBHOME}/nginx/clients/#{PROJECT}")		
	#Copy everything but the Rakefile
	files = Dir.glob("*")
	files.delete("Rakefile") 
	FileUtils.cp_r(files, "#{PUREWEBHOME}/nginx/clients/#{PROJECT}/")	
end

desc "Stage clean #{PROJECT}"
task :stageclean do
	FileUtils.rm_r("#{PUREWEBHOME}/nginx/clients/#{PROJECT}", :force => true)
end

desc "Build all the things for #{PROJECT}"
task :all do
	Rake::Task[:stageclean].invoke
	Rake::Task[:stage].invoke
	Rake::Task[:packageclean].invoke
	Rake::Task[:package].invoke
end

task :default do
	sh("rake -T")
end