project="Scribble"

purewebhome = ENV['PUREWEB_HOME']
pureweblibs = ENV['PUREWEB_LIBS']

desc "Clean #{project}"
task :clean do	
	FileUtils.rm_r("bower_components", :force => true)
end

desc "Setup #{project}"
task :setup do
	sh("bower install")
end

desc "Deploy #{project}"
task :deploy do
	Rake::Task[:stage].invoke
end

desc "Package #{project}"
task :package do
	puts "Need to implement PACKAGE for #{project}"
end

desc "Package clean #{project}"
task :packageclean do
	puts "Need to implement PACKAGECLEAN for #{project}"
end 

desc "Stage #{project}"
task :stage => [:setup] do	
	FileUtils.mkdir_p("#{purewebhome}/nginx/clients/#{project}")		
	#Copy everything but the Rakefile
	files = Dir.glob("*")
	files.delete("Rakefile") 
	FileUtils.cp_r(files, "#{purewebhome}/nginx/clients/#{project}/")		

	if File.exist?("#{pureweblibs}/HTML5/pureweb.min.js")
		FileUtils.mkdir_p("#{purewebhome}/nginx/clients/#{project}/lib/pureweb")		
		FileUtils.cp_r("#{pureweblibs}/HTML5/.", "#{purewebhome}/nginx/clients/#{project}/lib/pureweb")	
	end
end

desc "Stage clean #{project}"
task :stageclean do
	FileUtils.rm_r("#{purewebhome}/nginx/clients/#{project}", :force => true)
end

desc "Build all the things for #{project}"
task :all do |t|
	scope = t.scope.first || ''
	scope = scope.length > 0 ? scope + ":" : scope
	Rake::Task[scope+'stageclean'].invoke
	Rake::Task[scope+'stage'].invoke
	Rake::Task[scope+'packageclean'].invoke "release"
	Rake::Task[scope+'package'].invoke
end

task :default do
	sh("rake -T")
end